<p style="text-align: center;"><strong>NỘI QUY PH&Ograve;NG THI</strong></p>
<ol>
    <li style="text-align: justify; line-height: 2;">Th&iacute; sinh phải c&oacute; mặt tại địa điểm thi đ&uacute;ng ng&agrave;y giờ quy định. Nếu đến chậm qu&aacute; 15 ph&uacute;t sau khi đ&atilde; t&iacute;nh giờ l&agrave;m b&agrave;i th&igrave; kh&ocirc;ng được dự thi.</li>
    <li style="text-align: justify; line-height: 2;">Sau khi v&agrave;o ph&ograve;ng thi, th&iacute; sinh phải xuất tr&igrave;nh thẻ sinh vi&ecirc;n v&agrave; giấy CMND, ngồi đ&uacute;ng chỗ ghi số b&aacute;o danh trong ph&ograve;ng thi.</li>
    <li style="text-align: justify; line-height: 2;">Kh&ocirc;ng được mang v&agrave;o ph&ograve;ng thi t&agrave;i liệu c&oacute; chữ, giấy than, điện thoại di động, vũ kh&iacute;, chất g&acirc;y ch&aacute;y nổ, phương tiện kỹ thuật ph&aacute;t, truyền tin, ghi &acirc;m v&agrave; c&aacute;c vật dụng kh&aacute;c.</li>
    <li style="text-align: justify; line-height: 2;">Th&iacute; sinh kh&ocirc;ng mang theo tư trang đi thi. Nếu mang theo tư trang (bao gồm: c&aacute;c thiết bị ghi &acirc;m, ghi h&igrave;nh, thiết bị truyền th&ocirc;ng, giấy, b&uacute;t v&agrave; c&aacute;c vật dụng kh&aacute;c), th&iacute; sinh phải cất v&agrave;o khu vực quy định v&agrave; tự chịu tr&aacute;ch nhiệm về t&agrave;i sản của m&igrave;nh.</li>
    <li style="text-align: justify; line-height: 2;">Th&iacute; sinh chỉ được ph&eacute;p ra khỏi ph&ograve;ng thi sau khi ho&agrave;n th&agrave;nh hết 2/3 thời gian thi. Trường hợp ốm đau bất thường phải b&aacute;o c&aacute;o c&aacute;n bộ coi thi xử l&yacute;.</li>
    <li style="text-align: justify; line-height: 2;">Nghi&ecirc;m cấm mọi h&agrave;nh vi trao đổi, b&agrave;n bạc, gian lận, quay c&oacute;p. C&aacute;c trường hợp vi phạm sẽ bị nhắc nhở c&ocirc;ng khai v&agrave; bị xử l&yacute; kỷ luật theo c&aacute;c mức từ cảnh c&aacute;o đến đ&igrave;nh chỉ thi.</li>
    <li style="text-align: justify; line-height: 2;">Do t&iacute;nh bảo mật của đề thi, nghi&ecirc;m cấm th&iacute; sinh lấy th&ocirc;ng tin li&ecirc;n quan đến b&agrave;i thi dưới mọi h&igrave;nh thức. Th&iacute; sinh kh&ocirc;ng được sử dụng giấy nh&aacute;p.</li>
    <li style="text-align: justify; line-height: 2;">Trong qu&aacute; tr&igrave;nh l&agrave;m b&agrave;i, th&iacute; sinh kh&ocirc;ng tự &yacute; t&aacute;c động v&agrave;o m&aacute;y t&iacute;nh. Nếu c&oacute; bất kỳ vấn đề g&igrave; ph&aacute;t sinh, th&iacute; sinh giơ tay để gi&aacute;m thị giải quyết sự cố. Trước giờ thi th&iacute; sinh sẽ được xem hướng dẫn l&agrave;m b&agrave;i thi qua Video Clip.</li>
    <li style="text-align: justify; line-height: 2;">Khi kết th&uacute;c b&agrave;i thi, th&iacute; sinh giơ tay để gi&aacute;m thị đến kiểm tra. Th&iacute; sinh phải k&yacute; t&ecirc;n v&agrave;o danh s&aacute;ch trước khi ra ngo&agrave;i.</li>
    <li style="text-align: justify; line-height: 2;">Nếu th&iacute; sinh vi phạm c&aacute;c quy định tr&ecirc;n, sẽ bị đ&igrave;nh chỉ thi v&agrave; hủy kết quả thi.</li>
</ol>
