FROM dunglas/frankenphp

RUN install-php-extensions \
    pdo_mysql \
    gd \
    imap \
    bcmath \
    intl \
    msgpack \
    zip \
    igbinary \
    opcache \
    redis \
    memcached \
    pcov \
    imagick/imagick@master

COPY docker/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xml

RUN apt update && apt install -y software-properties-common wkhtmltopdf ghostscript npm
RUN npm install npm@latest -g && npm install n -g && n latest

RUN apt install -y gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libgbm-dev libxshmfence-dev
RUN npm install --location=global --unsafe-perm puppeteer@^17

ARG SERVER_NAME=:80

ENV SERVER_NAME=$SERVER_NAME

# Enable PHP production settings
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

WORKDIR /app

COPY app ./app
COPY bootstrap ./bootstrap
COPY config ./config
COPY database ./database
COPY lang ./lang
COPY nova-components ./nova-components
COPY packages ./packages

COPY public/build ./public/build
COPY public/vendor ./public/vendor
COPY public/.htaccess ./public/.htaccess
COPY public/favicon.ico ./public/favicon.ico
COPY public/index.php ./public/index.php
COPY public/robots.txt ./public/robots.txt

COPY resources ./resources
COPY routes ./routes
COPY vendor ./vendor
COPY artisan .
COPY composer.json .
COPY composer.lock .

COPY docker/memory.ini /usr/local/etc/php/conf.d/memory.ini

RUN mkdir -p storage/app/public
RUN mkdir -p storage/framework/views
RUN mkdir -p storage/framework/cache/data
RUN mkdir -p storage/framework/sessions
RUN mkdir -p storage/framework/testing
RUN mkdir -p storage/logs

RUN ln -s /app/storage/app/public public/storage
